export const portfolioData = {
  name: "Muhammad Abdul Halim",
  role: "Full-Stack Developer",
  tagline: "Building digital experiences across Web2, Web3, and AI — passionate about finance, technology, and innovation.",
  bio: `I'm a 4th semester Informatics student at Universitas Singaperbangsa Karawang (UNSIKA) with a passion for web development, AI, and blockchain technology.

Currently exploring modern web stacks like Next.js, Node.js, and FastAPI while actively participating in organizations, hackathons, and research competitions. I believe in building technology that makes a real impact — from financial literacy platforms to AI-powered waste sorting systems.`,
  location: "Karawang, Indonesia",
  email: "halimjunior52@gmail.com",
  socials: [
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/abdulhalim-dev/",
      icon: "linkedin",
    },
    {
      name: "GitHub",
      url: "https://github.com/AbdulHalim26",
      icon: "github",
    },
  ],
  skills: [
    { name: "HTML", category: "frontend" as const },
    { name: "CSS", category: "frontend" as const },
    { name: "JavaScript", category: "frontend" as const },
    { name: "TypeScript", category: "frontend" as const },
    { name: "React", category: "frontend" as const },
    { name: "Next.js", category: "frontend" as const },
    { name: "Tailwind CSS", category: "frontend" as const },
    { name: "Node.js", category: "backend" as const },
    { name: "FastAPI", category: "backend" as const },
    { name: "PostgreSQL", category: "backend" as const },
    { name: "MongoDB", category: "backend" as const },
    { name: "Java", category: "backend" as const },
    { name: "bcrypt", category: "backend" as const },
    { name: "VS Code", category: "other" as const },
    { name: "Vercel", category: "other" as const },
    { name: "Railway", category: "other" as const },
    { name: "Resend", category: "other" as const },
    { name: "Opencode", category: "other" as const },
    { name: "Git", category: "other" as const },
    { name: "GitHub", category: "other" as const },
    { name: "Jira", category: "other" as const },
    { name: "Antigravity", category: "other" as const },
    { name: "Kiro", category: "other" as const },
    { name: "GLM", category: "other" as const },
    { name: "Cisco", category: "networking" as const },
  ],
  experiences: [
    {
      title: "Informatics Engineering",
      organization: "Universitas Singaperbangsa Karawang",
      period: "2024 - 2028",
      description: "Pursuing a degree in Informatics Engineering with a current GPA of 3.84. Focused on web development, AI, and blockchain technology.",
      type: "education" as const,
    },
    {
      title: "Anggota Komisi A",
      organization: "BEM FASILKOM UNSIKA",
      period: "2026 - 2027",
      description: "Active member of the student executive board, contributing to organizational development and student welfare initiatives.",
      type: "work" as const,
    },
    {
      title: "PKM-KC",
      organization: "Universitas Singaperbangsa Karawang",
      period: "2026",
      description: "Represented Universitas Singaperbangsa Karawang in PKM-KC (Program Kreativitas Mahasiswa - Karsa Cipta) at the national level.",
      type: "achievement" as const,
    },
    {
      title: "Peserta Hackathon Frontier Colloseum",
      organization: "Global Web3 Event",
      period: "2026",
      description: "Participated in the Frontier Colloseum global Web3 hackathon, competing in blockchain and decentralized application development.",
      type: "achievement" as const,
    },
    {
      title: "Peserta Web Development Polindra",
      organization: "BlockDev Ethereum Network",
      period: "2026",
      description: "Participated in web development competition organized by Polindra, blockchain track by BlockDev on Ethereum network.",
      type: "achievement" as const,
    },
    {
      title: "Finalis BPC (Business Plan Competition)",
      organization: "UNRAM",
      period: "2026",
      description: "Finalist in the Business Plan Competition but unable to attend due to travel costs to UNRAM.",
      type: "achievement" as const,
    },
    {
      title: "AI Medical Waste Sorting System",
      organization: "Pekan IT - Himpunan IoT",
      period: "2026",
      description: "AI-based medical waste sorting system selected from multiple groups to be showcased at the IT competition of the IoT association.",
      type: "achievement" as const,
    },
  ],
  projects: [
    {
      title: "IHSG Platform",
      description: "Financial literacy platform designed for young Indonesians to understand the stock market (IHSG). Built with modern web technologies for an intuitive learning experience.",
      tech: ["Next.js", "TypeScript", "Tailwind CSS"],
      links: {
        live: "https://abdulhalim.vercel.app",
      },
      highlight: true,
    },
    {
      title: "Autosup",
      description: "AI-powered business restock platform integrated with Solana Web3. Features AI agentic automation for supply chain management on the blockchain.",
      tech: ["Next.js", "FastAPI", "Solana Web3", "AI", "TypeScript"],
      links: {
        live: "https://autosup.vercel.app/auth/login",
      },
      highlight: true,
    },
    {
      title: "UMKMDesaGandoang",
      description: "Village UMKM web platform developed as a final project for the RPL (Software Engineering) course. Presented at a national seminar. Handled full authentication system as a fullstack developer.",
      tech: ["Next.js", "Node.js", "PostgreSQL", "Tailwind CSS"],
      links: {},
      highlight: true,
    },
    {
      title: "AI Medical Waste Sorting System",
      description: "AI-based system for sorting medical waste, developed for the EIS (Enterprise Information System) course. Selected from multiple groups to be showcased at the IT competition of the IoT association.",
      tech: ["AI", "Python", "IoT", "Machine Learning"],
      links: {},
      highlight: true,
    },
    {
      title: "SIREFA - Sistem Reservasi Fasilitas Aula",
      description: "Aula reservation system built with Java on Netbeans. Provides facility booking management for institutional use.",
      tech: ["Java", "Netbeans"],
      links: {},
    },
    {
      title: "Ragakopi",
      description: "Interactive web project for the Human-Computer Interaction course. Explores the origins, locations, and cultural significance of coffee.",
      tech: ["Google Sites", "Web Design"],
      links: {
        live: "https://sites.google.com/view/ragakopi/home",
      },
    },
    {
      title: "Sentiment Analysis - Mie Gacoan Karawang",
      description: "Research article draft analyzing public sentiment towards Mie Gacoan Karawang using the Naive Bayes algorithm. Dataset obtained through web scraping techniques.",
      tech: ["Naive Bayes", "Python", "Web Scraping", "Data Mining"],
      links: {},
    },
  ],
}
